### ISSUE TITLE
How to use credentials ID for CasC in 1.0.0 version?

### ISSUE THREAD

**Issue by denis-matchenko** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#195]
### Describe your use-case which is not covered by existing documentation.

In version `0.5.6` we used the Credentials ID set as a variable (using CasC) but it doesn't work in the new version.

CasC example:

```
unclassified:
  metricsAccessKey:
    accessKeys:
      - canHealthCheck: false
        canMetrics: false
        canPing: true
        canThreadDump: false
        description: "Metrics Plugin"
        key: "${metrics-id}"                            // it doesn't work
        origins: "*"
```
