### ISSUE TITLE
How to setup username/password with JCasC

### ISSUE THREAD

**Issue by soham-chakraborty1** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#225]
### Describe your use-case which is not covered by existing documentation.

Hi,

I am trying to set up username/password combination with aws secrets manager credential provider plugin. I have created the secret in AWS secrets manager.

Now I am trying to set it up with CasC. I am using  https://github.com/jenkinsci/helm-charts to set it up. But I am having a hard time figuring it out. Should it be something like this: 

```
  JCasC:
    defaultConfig: true
    configScripts: {}
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    # Ignored if authorizationStrategy is defined in controller.JCasC.configScripts
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    unclassified:
      awsCredentialsProvider:
      cache: (boolean)                 # optional
      client:                          # optional
        credentialsProvider: (object)  # optional
        endpointConfiguration:         # optional
          serviceEndpoint: (URL)
          signingRegion: (string)
      region: (string)               # optional
      listSecrets:                     # optional
        filters:
          - key: name
            values:
              - dockerhub
          - key: tag-key
            values:
              - jenkins:credentials:type
          - key: tag-value
            values:
              - usernamePassword
          - key: description
            values:
              - "dockerhub for Jenkins"
      transformations:           # optional
        description:
          hide: {}
        name:
          removePrefix:
            prefix: (string)
```

Do you think this information would be useful in documentation?

**Comment by chriskilding** [comment]
1. As indicated in the README, the CasC snippet provided in the README is a schema, not a concrete example. So for example, `region: (string)` indicates the region field takes string values. You need to substitute your actual environment's value for the placeholder at that point.

2. Omitting a field from CasC configuration just means **the field inherits a sensible default**. In general, **don't set a field in CasC unless the default value does not work for you**. You want to set the minimum number of attributes in CasC that you need. I recommend developing your Jenkins CasC configuration in an iterative TDD-like cycle, so you can narrow down what works.

3. Set only the filters you need, because these will filter out anything that doesn't match. Definitely do not filter on the `jenkins:credentials:type` tag, because if you do this, no credentials of other types can appear. Additionally it is inadvisable to filter on the secret description, since this is field is really to help human operators understand what a secret does; there are better fields to filter on.

**Comment by soham-chakraborty1** [comment]
Hi @chriskilding ,

Thank you for your response. I followed your advice and now my `values.yaml` looks like this: 

```
controller:
  componentName: "jenkins-controller"
  <SNIP>
  JCasC:
    defaultConfig: true
    configScripts: {}
    #  welcome-message: |
    #    jenkins:
    #      systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
    # Ignored if securityRealm is defined in controller.JCasC.configScripts and
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    # Ignored if authorizationStrategy is defined in controller.JCasC.configScripts
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    unclassified:
      awsCredentialsProvider:
      cache: (boolean)                 # optional
      client:                          # optional
        credentialsProvider: (object)  # optional
        endpointConfiguration:         # optional
          serviceEndpoint: (URL)
          signingRegion: (string)
      region: (string)               # optional
      listSecrets:                     # optional
        filters:
          - key: name
            values:
              - (string)
          - key: tag-key
            values:
              - (string)
          - key: tag-value
            values:
              - (string)
          - key: description
            values:
              - (string)
      transformations:           # optional
        description:
          hide: {}
        name:
          removePrefix:
            prefix: (string)  
```

What I am observing with this is that the secrets that I have already created in AWS are automatically showing up in my Jenkins web UI. So I am *guessing* is that the plugin is doing all the heavy lifting and that's awesome!

**Comment by chriskilding** [comment]
I've noticed something subtle in the config you pasted:

```
unclassified:
  awsCredentialsProvider:
  cache: (boolean)
  # ...all the other properties
```

All the properties that you intended to be for the awsCredentialsProvider are in fact siblings of it rather than children of it.

Because they are siblings, they have no effect on the plugin. This means that effectively you're running the plugin with entirely default settings. And, as I anticipated, the plugin works just fine with the defaults.

Therefore I recommend deleting all the extra stuff you've got in there, because you don't need it:

```
      cache: (boolean)                 # optional
      client:                          # optional
        credentialsProvider: (object)  # optional
        endpointConfiguration:         # optional
          serviceEndpoint: (URL)
          signingRegion: (string)
      region: (string)               # optional
      listSecrets:                     # optional
        filters:
          - key: name
            values:
              - (string)
          - key: tag-key
            values:
              - (string)
          - key: tag-value
            values:
              - (string)
          - key: description
            values:
              - (string)
      transformations:           # optional
        description:
          hide: {}
        name:
          removePrefix:
            prefix: (string)  
```
