### ISSUE TITLE
Can we pass googleoauth2 parameters in the helm chart with this plugin

### ISSUE THREAD

**Issue by soham-chakraborty1** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#232]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
Jenkins version is 2.46.3
Helm chart version: 4.1.17

AWS secrets manager Credential provider plugin version: 1.2.0
AWS secrets manager secretsource plugin version: 0.0.2

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Use the following helm values file:

```
controller:
  ...
  JCasC:
    defaultConfig: true
    configScripts: {}
    #  welcome-message: |
    #    jenkins:
    #      systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
    # Ignored if securityRealm is defined in controller.JCasC.configScripts and
    securityRealm: |-
      googleOAuth2:
        clientId: test_google_client_Id
        clientSecret: test_google_client_secret
        domain: ""
```

The secrets are present in AWS secrets manager with the right name and the tag `jenkins:credentials:type: string`.

Now when I install/upgrade the chart, the values are directly sent to Jenkins without the interpolation. So the string `test_google_client_id` is sent and not the actual value inside of the secret. 

Is this expected behavior? In other words, I am trying to save the secrets and then pass them using JCaSC. 

If this cannot be achieved in this manner, what other options do I have to securely pass the secrets and not dump them in git :) https://github.com/jenkinsci/helm-charts/issues/674#issuecomment-1221575794 shows how to do this without encrypting them.

### Expected Results

Jenkins should start up with shiny Google Oauth credentials.

### Actual Results

Get a 401 no ouath2 client error.
