### ISSUE TITLE
casc config reports improper filter value

### ISSUE THREAD

**Issue by bentlifetattoo** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#265]
### Jenkins and plugins versions report

when viewing the casc config, the filter value is reported as the object address.

``` 
 listSecrets:
      filters:
      - key: "name"
        values:
        - "io.jenkins.plugins.credentials.secretsmanager.config.Value@5cd22463"
```
        

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

add a filter, view casc config

### Expected Results

the value of the filter is displayed

### Actual Results

object value displayed
