### ISSUE TITLE
Prefix removal does not work while using Cache after Jenkins Restart

### ISSUE THREAD

**Issue by ben-dov** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#328]
### Jenkins and plugins versions report

plugin is version 1.214.va_0a_d8268d068

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

1. create a secret in secret store named "myprefix/mysecret"
2. use jenkins helm to setup the plugin using using CASC
3. under the plugin config configure
```
 cache: true
 transformations:
      name:
        removePrefix:
          prefix: "myprefix/"
```
4. restart jenkins

### Expected Results

secret ID should be `mysecret`

### Actual Results

secret ID is `myprefix/mysecret`

### Anything else?

change cache to false, and restart.
notice the issue does not happen (but now we cant use cache, or we have to manually trigger it)
