### ISSUE TITLE
Allow AWS access key to be specified inline within Jenkins plugin config

### ISSUE THREAD

**Issue by DimaNevelev** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#94]
### Feature Request
In my organization, every team has its own Jenkins instance running on K8S. This K8s and the instances are managed by an allocated team. 
Since this is K8s we can't just give roles to the nodes (ec2 instances) because we need segregation between the teams.
They can set [IAM role for a service account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), but we don't want to go this path because it will be hard to maintain...
Instead, we want to give the teams API keys (functional users) and roles to access the AWS secrets manager. 
The problem is they have access only to the Jenkins UI, and they can't edit the infrastructure. i.e., EnvVars, Java props, user profile authentication are out of the scope...
I would like to have the ability to set up my AWS API key+secret (or credentials id) and AWS role that will be used to pull the credentials...
p.s. Any workaround will be appreciated.

**Comment by chriskilding** [comment]
Just to check I understand the surrounding context right...

- Your company has 1 big AWS account for all teams
- All teams' secrets are in that account's Secrets Manager
- Each team has a K8S-on-EC2 cluster (not EKS?) with Jenkins on it

**Comment by chriskilding** [comment]
Also, are the teams able to edit resources in the AWS account besides the locked-down K8S clusters (i.e. can they put their own secrets in Secrets Manager), or does some central team or enterprise automation tooling edit the AWS resources for them?

**Comment by DimaNevelev** [comment]
* Your company has 1 big AWS account for all teams:
   - We have multiple AWS accounts, two of them are dedicated to Secrets manager (Dev and Prod) 
* All teams' secrets are in that account's Secrets Manager:
   - Yes, all the secrets are stored in two main aws accounts. There is a segregation between the teams via roles based on the secret's name. For example, team AAA has access only to secrets with the name "/aaa/*".  
* Each team has a K8S-on-EC2 cluster (not EKS?) with Jenkins on it
   - Each team has a namespace with Jenknis instance in a dedicated for Jenkins K8s. This K8s runs on ec2 nodes/instances (not EKS) in a separate account from the accounts used for secrets manager.  
* are the teams able to edit resources in the AWS account
  - The teams can edit their secrets and change their API keys in the secrets manager account. They can't change the resources of the Jenkins K8s account.

**Comment by chriskilding** [comment]
Ok, the first thing to find out is whether you can use AWS profiles to let the Jenkins box hop into the alternate account for Secrets Manager access; if this can't be done then we'll have to deal with this first.

This plugin doesn't currently support *multiple* accounts for lack of a good credential namespacing solution. However I believe AWS lets you use a *different* account to the implicit one, by specifying an assumeRole ARN if you set up an AWS profile in ~/.aws/config and ~/.aws/credentials. Give that a go, and if that works we can look at improving the way config works.

**Comment by DimaNevelev** [comment]
We can't / don't want the Jenkins infrastructure to be involved. Since ~/.aws/credentials are defined in the infrastructure, we can't do this...
A great solution for us would be an integration with the [aws-credentials plugin](https://docs.cloudbees.com/plugins/ci/aws-credentials). The user will set up aws-credentials and choose the relevant credentials in the plugin configuration. The plugin will use these credentials to pull the secrets from the secrets manager service...
The downside of this solution is the dependency on the aws-credentials plugin.

**Comment by chriskilding** [comment]
I'm planning to restore a part of the beta `clients` feature which should do what you need. This would expose a `client:` option in the config that would allow you to change the following fields about the AWS SDK client, including the AWS `credentialsProvider` which tells the SDK which strategy to authenticate with. The `static` strategy would allow an access key pair to be specified inline within Jenkins config, rather than inherited from outside:

```yaml
<plugin>:
  cache: ...
  client:
    credentialsProvider:
      static:  # options: blank (default), static (specify key pair inline - shown here), profile (read from AWS profiles), assumeRole (IAM role ARNs)
        accessKeyId: "foo"
        secretAccessKey: "bar"
    endpointConfiguration: # or leave blank for default
      serviceEndpoint: ...
      signingRegion: ...
    region: "some-region" # or leave blank for default
  listSecrets:
    filters:
      ...
```

Let me know if this does what you need (I think it should?)

**Comment by DimaNevelev** [comment]
This is pretty close to what we need...
Two things I would like to change:
1. Providing the secretAccessKey as plain text in Jenkins configuration is a high-security risk. 
I think a preferred (and the standard) way is to store the accessKeyId and secretAccessKey as credentials in Jenkins. 
2. We need a combination of static and role. 
```
    credentialsProvider:
      static:  # options: blank (default), static (specify credentials ID - shown here), profile (read from AWS profiles), assumeRole (IAM role ARNs)
        credentialsId: "AWSCredentials" // the id of the credentials in Jenkins 
        role: ... // the role to assume
```
If you don't have the time for these two requests, let me know... restore the clients, and I will contribute it.
